# Generated by Django 5.0.3 on 2024-07-16 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='datasets/')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_variables', models.TextField()),
                ('output_variable', models.CharField(max_length=100)),
                ('num_units', models.IntegerField()),
                ('num_layers', models.IntegerField()),
                ('activation_function', models.CharField(max_length=50)),
                ('epochs', models.IntegerField()),
                ('optimizer', models.CharField(max_length=50)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeseries.dataset')),
            ],
        ),
    ]
