# Generated by Django 5.0.3 on 2024-07-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeseries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingparameters',
            name='output_variable',
        ),
        migrations.AddField(
            model_name='trainingparameters',
            name='output_variables',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='trainingparameters',
            name='input_variables',
            field=models.CharField(max_length=200),
        ),
    ]
